name: .NET Tool Release

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --configuration Release /p:OfficialBuild=true
    - name: Publish NuGet to Nuget.org
      run: dotnet nuget push ./src/dotnex/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TOKEN }} --skip-duplicate
    - name: Publish to GitHub packages
      run: dotnet nuget push ./src/dotnex/bin/Release/*.nupkg --source https://nuget.pkg.github.com/piraces/index.json -k ${{ secrets.GITHUB_TOKEN }}  --skip-duplicate
