name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x', '5.0.x', '6.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies ${{ matrix.dotnet }}
      run: dotnet restore
    - name: Build ${{ matrix.dotnet }}
      run: dotnet build --no-restore
    - name: Test ${{ matrix.dotnet }}
      run: dotnet test --no-build --verbosity normal